/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food.date.manager;

import java.sql.SQLException;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akash
 */
public class AddPacketFrame extends javax.swing.JFrame {

    /**
     * Creates new form addPacketFrame
     */
    MyJFrame frameInstance;
    DefaultComboBoxModel dropDownModel;
    DefaultTableModel tableModel;
    public AddPacketFrame(DefaultTableModel tableModel, MyJFrame frame) {
        this.frameInstance = frame;
        initComponents();
        this.tableModel = tableModel;
        try {
            dropDownModel =  new DefaultComboBoxModel<>(InventoryDBManager.getInstance().getItemTypes());
            dropDown.setModel(dropDownModel);
        } catch(Exception e) {
            e.printStackTrace();
        }
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        itemTypeLabel = new javax.swing.JLabel();
        dropDown = new javax.swing.JComboBox<>();
        expirationLabel = new javax.swing.JLabel();
        monthField = new javax.swing.JTextField();
        dayField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        openedCheckBox = new javax.swing.JCheckBox();
        addItemTypeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemTypeLabel.setText("Item Type:");

        dropDown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        expirationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        expirationLabel.setText("Expiration (mm/dd/yy):");

        monthField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dayField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        yearField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("/");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("/");

        openedCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        openedCheckBox.setText("Opened");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(openedCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(expirationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dayField, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dropDown, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(itemTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dayField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expirationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthField)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yearField)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openedCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        addItemTypeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addItemTypeButton.setText("Add New Item Type");
        addItemTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemTypeButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addItemTypeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(addItemTypeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Scanner scan = new Scanner(yearField.getText());
        int year;
        if(scan.hasNextInt()) {
            year = scan.nextInt();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid date");
            return;
        }
        scan = new Scanner(monthField.getText());
        int month;
        if(scan.hasNextInt()) {
            month = scan.nextInt();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid date");
            return;
        }
        scan = new Scanner(dayField.getText());
        int day;
        if(scan.hasNextInt()) {
            day = scan.nextInt();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid date");
            return;
        }        
        Date date;
        try {
            date = new SimpleDateFormat("dd-MM-yyyy").parse(day+"-"+month+"-"+year);
            if(Calendar.getInstance().getTime().compareTo(date)>0) {
                JOptionPane.showMessageDialog(this, "Product has already expired. Please dispose it");
                throw new Exception();
            }

            String name = dropDown.getSelectedItem().toString();
            InventoryDBManager DB = InventoryDBManager.getInstance();
            boolean b = openedCheckBox.isSelected();

            b = DB.addItem(name, date,b);
            if(!b) {
                JOptionPane.showMessageDialog(this, "Opened chub already exists. Please consume existing chub before adding new open chub");
                throw new Exception();
            }
            tableModel.setDataVector(DB.getInventory(), 
                    new String[] {"Item Number", "Name", "Sell By", "Opened"});
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid date");
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch(NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Please add item type");
        } catch (Exception ex) {
            ex.printStackTrace();
        } 
        frameInstance.expiredPanel.updateTable();
        this.dispose();
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void addItemTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemTypeButtonActionPerformed
        AddItemFrame frame = new AddItemFrame(dropDownModel);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame.setLocationRelativeTo(frameInstance);
                frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_addItemTypeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addItemTypeButton;
    private javax.swing.JTextField dayField;
    private javax.swing.JComboBox<String> dropDown;
    private javax.swing.JLabel expirationLabel;
    private javax.swing.JLabel itemTypeLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField monthField;
    private javax.swing.JCheckBox openedCheckBox;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
