package food.date.manager;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Akash
 */
public class Home extends javax.swing.JPanel {
    MyJFrame frameInstance;
    InventoryDBManager DBInstance;
    FoodMap foodMap;
    Color sidePaneDefault = new Color(51,153,255);
    Color sidePaneSelected = new Color(0,0,255);
    /**
     * Creates new form Home
     */
    public Home(MyJFrame instance) {
        initComponents();
        DBInstance = InventoryDBManager.getInstance();
        foodMap = FoodMap.getInstance();
        this.frameInstance = instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePane = new javax.swing.JPanel();
        homeTab = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        inventoryTab = new javax.swing.JPanel();
        inventoryLabel = new javax.swing.JLabel();
        expiredTab = new javax.swing.JPanel();
        expiredLabel = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        itemTextField = new javax.swing.JTextField();
        itemLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        sidePane.setBackground(new java.awt.Color(51, 102, 255));

        homeTab.setBackground(new java.awt.Color(51, 153, 255));
        homeTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeTabClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeTabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeTabMouseExited(evt);
            }
        });

        homeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setText("HOME");

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        inventoryTab.setBackground(new java.awt.Color(51, 153, 255));
        inventoryTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTabClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryTabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryTabMouseExited(evt);
            }
        });

        inventoryLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        inventoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        inventoryLabel.setText("INVENTORY");

        javax.swing.GroupLayout inventoryTabLayout = new javax.swing.GroupLayout(inventoryTab);
        inventoryTab.setLayout(inventoryTabLayout);
        inventoryTabLayout.setHorizontalGroup(
            inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        inventoryTabLayout.setVerticalGroup(
            inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inventoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        expiredTab.setBackground(new java.awt.Color(51, 153, 255));
        expiredTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expiredTabClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                expiredTabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                expiredTabMouseExited(evt);
            }
        });

        expiredLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        expiredLabel.setForeground(new java.awt.Color(255, 255, 255));
        expiredLabel.setText("EXPIRED ITEMS");

        javax.swing.GroupLayout expiredTabLayout = new javax.swing.GroupLayout(expiredTab);
        expiredTab.setLayout(expiredTabLayout);
        expiredTabLayout.setHorizontalGroup(
            expiredTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expiredTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expiredLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        expiredTabLayout.setVerticalGroup(
            expiredTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expiredTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expiredLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sidePaneLayout = new javax.swing.GroupLayout(sidePane);
        sidePane.setLayout(sidePaneLayout);
        sidePaneLayout.setHorizontalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inventoryTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(expiredTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePaneLayout.setVerticalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePaneLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(homeTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expiredTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        searchLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        searchLabel.setText("Search");

        itemTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemLabel.setText("Item Number:");

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 601, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeTabClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTabClicked
        frameInstance.setFrame("home");
    }//GEN-LAST:event_homeTabClicked

    private void inventoryTabClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTabClicked
        frameInstance.setFrame("inventory");
    }//GEN-LAST:event_inventoryTabClicked

    private void expiredTabClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiredTabClicked
        frameInstance.setFrame("expired");
    }//GEN-LAST:event_expiredTabClicked

    private void homeTabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTabMouseEntered
        homeTab.setBackground(sidePaneSelected);
    }//GEN-LAST:event_homeTabMouseEntered

    private void homeTabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTabMouseExited
        homeTab.setBackground(sidePaneDefault);
    }//GEN-LAST:event_homeTabMouseExited

    private void inventoryTabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTabMouseEntered
        inventoryTab.setBackground(sidePaneSelected);
    }//GEN-LAST:event_inventoryTabMouseEntered

    private void inventoryTabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTabMouseExited
        inventoryTab.setBackground(sidePaneDefault);
    }//GEN-LAST:event_inventoryTabMouseExited

    private void expiredTabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiredTabMouseEntered
        expiredTab.setBackground(sidePaneSelected);
    }//GEN-LAST:event_expiredTabMouseEntered

    private void expiredTabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiredTabMouseExited
        expiredTab.setBackground(sidePaneDefault);
    }//GEN-LAST:event_expiredTabMouseExited

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if(itemTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(frameInstance, "Please Enter an Item Number");
            return;
        }
        String item = itemTextField.getText();
        itemTextField.setText("");
        boolean found = foodMap.isOpened(item);
        if(found) {
            try {
                JOptionPane.showMessageDialog(frameInstance, "Opened Chub was found!");
                packetUsed(item);
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                JOptionPane.showMessageDialog(frameInstance, "Opened Chub was not found!");
                findClosed(item);
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    public void packetUsed(String item) throws SQLException {
        if(JOptionPane.showConfirmDialog(frameInstance, "Did you use up the packet?", "Packet Found", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            DBInstance.deleteItem(foodMap.get(item));
            frameInstance.inventoryPanel.updateTable();
            findClosed(item);
        }
    }
    
    public void findClosed(String item) throws SQLException {
        String[] row = DBInstance.findClosed(item);
        if(row!=null) {
            if(JOptionPane.showConfirmDialog(frameInstance, "A packet was found that expires at "+ row[2] +"\nDo you want to open this packet?", "Packet Found", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                OpenFrame frame = new OpenFrame(row, frameInstance);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            frame.setLocationRelativeTo(frameInstance);
                            frame.setVisible(true);
                            
                        }
                    });
                //packetUsed(item);
            }
        } else {
            JOptionPane.showMessageDialog(frameInstance, "Item was not found in inventory!");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel expiredLabel;
    private javax.swing.JPanel expiredTab;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homeTab;
    private javax.swing.JLabel inventoryLabel;
    private javax.swing.JPanel inventoryTab;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JTextField itemTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel sidePane;
    // End of variables declaration//GEN-END:variables
}
